### ISSUE TITLE
More specific package name

### ISSUE THREAD

**Issue by gaborcsardi** [nathaneastwood/hooks#1]
Maybe?

**Comment by nathaneastwood** [comment]
Any suggestions? My plan is to add more useful hooks as and when I find them which is why I chose a more generic name to start with

**Comment by gaborcsardi** [comment]
Well, if they are for knitr, then _knitrhooks_?

**Comment by gaborcsardi** [comment]
Also, technically, they are not really hooks, are they?

**Comment by nathaneastwood** [comment]
Technically, no, I'm wrapping knitr hooks into functions to provide additional chunk options. It could maybe be called *knitropts* or *knitrhooks* in that case?

**Comment by gaborcsardi** [comment]
I think knitrhooks sounds better. And knitting hooks are a thing, apparently. :)
